version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: main/Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./main:/app
    restart: always

  frontend:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: ui
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always
