[package]
name = "fastevaluate"
version = "0.1.0"
edition = "2024"

[lib]
name = "fastevaluate"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }
numpy = "0.22"
ndarray = { version = "0.16", features = ["rayon", "blas"] }
rayon = "1.10.0"